<a href="https://colab.research.google.com/github/rohanpashikanti/Data_Analytics/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np

arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
print(type(arr1))

<class 'numpy.ndarray'>


In [3]:
print(arr1.shape)

(3,)


In [4]:
print(arr1[2])

3


In [5]:
arr1[2] = 5
print(arr1)

[1 2 5]


In [8]:
arr2 = np.array([[1,2,3],[3,4,5]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [3 4 5]]
(2, 3)


In [15]:
print(arr2[1][2])
print(arr2[1,2])
print(arr2[1,-2])

5
5
4


In [17]:
arrs = np.array(['ind','china','usa','mexico'])
arrs

array(['ind', 'china', 'usa', 'mexico'], dtype='<U6')

In [19]:
arrr = np.arange(0,50,5)
print(arrr)

[ 0  5 10 15 20 25 30 35 40 45]


In [26]:
arrr = np.linspace(2,20,10)
arrr

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [29]:
print(np.zeros(10))
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [35]:
print(np.repeat(arr1,3))
print(np.tile(arr1,3))

[1 1 1 2 2 2 5 5 5]
[1 2 5 1 2 5 1 2 5]


In [37]:
 matrix = np.eye(3)
 matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])